### ISSUE TITLE
Psalm/PHPStan extensions suggested although already enabled (globally)

### ISSUE THREAD

**Issue by greg0ire** [phpactor/phpactor#2159]
I have a config file with Psalm and PHPStan enabled globally: https://github.com/greg0ire/dotfiles/blob/main/.config/phpactor/phpactor.yml#L13-L14

When I open nvim, PHPActor suggests I enable both extensions. It should IMO do nothing if the extensions are already enabled globally.

**Comment by dantleech** [comment]
yes, it could check the loaded files to see if the options were explicitly defined I expect.

**Comment by mamazu** [comment]
Where would the code for that be? Then I will have a look at it.

**Comment by mamazu** [comment]
I think the problem is the fact that you are using yaml.

With the following configuration:
```json
{
   "language_server_phpstan.enabled": false,
   "language_server_psalm.enabled": true,
   "language_server_php_cs_fixer.enabled": true,
   "prophecy.enabled": true
}
```

The suggester here find it and properly exists early:
https://github.com/phpactor/phpactor/blob/efe81d28b45b8ab04422711091ca1a3bd681983f/lib/Extension/LanguageServerPsalm/LanguageServerPsalmSuggestExtension.php#L25

However, the same object in yaml format:
```yaml
language_server_phpstan.enabled: false
language_server_psalm.enabled: true
language_server_php_cs_fixer.enabled: true
prophecy.enabled: true
```
Creates an empty JsonConfiguration and therefore the line `$config->has(...)` returns false.
