### ISSUE TITLE
Request for additional  phpstan integration

### ISSUE THREAD

**Issue by Goku-San** [phpactor/phpactor#2407]
Hello,

This is a request for additional phpstan integration if its possible...
I use Vim and have coc-nvim installed and I have set up language server in `coc-settings.json` 
```json
  "languageserver": {
    "phpactor": {
      "command": "~/.vim/autoload/plugged/phpactor/bin/phpactor",
      "args": ["language-server"],
      "trace.server": "verbose",
      "filetypes": ["php"]
    }
  }
```
In `~/.config/phpactor/phpactor.yml` I have set these options according to [language-server-phpactor-bin](https://phpactor.readthedocs.io/en/master/reference/configuration.html#language-server-phpactor-bin)
```yaml
language_server_phpstan.enabled: true
language_server_phpstan.bin: ~/.config/composer/vendor/bin/phpstan
language_server.diagnostics_on_update: false
language_server_completion.trim_leading_dollar: true
```
Could you please add config options if possible, for 
```yaml
language_server_phpstan.memoryLimit: 'to set memory limit ex. 1024M or 1G.. or what ever ram memory desired'
language_server_phpstan.configFile: 'for config file ex. ~/.config/composer/phpstan.neon'
```
With these two options I think the phpstan integration will be complete, especially with the second option because I can use global ``phpstan.neon`` file that will work say for all Laravel projects in my case.

Thanks...
