### ISSUE TITLE
when auto complete will double '$' 

### ISSUE THREAD

**Issue by dong8yong8** [phpactor/phpactor#2648]
i use helix-editor 24.03

when auto complete variable, there will be two '$"

example:
$test = 12;
next line input  '$t' , then auto complete $test, it will be : $$test

**Comment by dantleech** [comment]
i have no idea why Helix would behave differently here, howrever you can try:

https://phpactor.readthedocs.io/en/master/reference/configuration.html?highlight=dollar#language-server-completion-trim-leading-dollar

**Comment by przepompownia** [comment]
It comes from the case when I had dollar sign in (local to buffer) `iskeyword` variable in Vim/Neovim (https://github.com/phpactor/phpactor/issues/904). I'm not familiar with Helix, but I would expect it has an `iskeyword` equivalent.

**Comment by AsymetricData** [comment]
> i have no idea why Helix would behave differently here, howrever you can try:
> 
> https://phpactor.readthedocs.io/en/master/reference/configuration.html?highlight=dollar#language-server-completion-trim-leading-dollar

This works with Helix indeed.

**Comment by covaleski** [comment]
> > i have no idea why Helix would behave differently here, howrever you can try:
> > https://phpactor.readthedocs.io/en/master/reference/configuration.html?highlight=dollar#language-server-completion-trim-leading-dollar
> 
> This works with Helix indeed.

Also works for Kate. I had the same problems with dollar signs.

My current user config:

```json
{
    "servers": {
        "php": {
            "command": [
                "phpactor",
                "language-server",
                "--config-extra={\"language_server_completion.trim_leading_dollar\":true}"
            ],
            "root": ".",
            "url": "https://github.com/phpactor/phpactor",
            "highlightingModeRegex": "^PHP.*$"
        }
    }
}
```

**Comment by LeoniePhiline** [comment]
Would you accept a PR adjusting https://phpactor.readthedocs.io/en/master/lsp/helix.html, adding the extra config argument?

i.e.

```toml
# in <config_dir>/helix/languages.toml

[language-server.phpactor]
command = "phpactor"
args = [
  "language-server",
  # Workaround for https://github.com/phpactor/phpactor/issues/2648
  "--config-extra={ \"language_server_completion.trim_leading_dollar\": true }"
]

[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp"]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
comment-token = "//"
language-servers = [ "phpactor" ]
indent = { tab-width = 4, unit = "    " }
```
