### ISSUE TITLE
Teleport to different aspects of the source code

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#37]
Create a feature which will allow easy navigation to / or generation of related files (e.g. from a unit test, the source, from the source the unit test, from the unit test the benchmark, etc. etc. etc.)

---

Below each target represents an aspect of the source code, for example

- Source
- Unit test
- Benchmark

The **kernel** is the part of the file name (or class name) which remains constant.

When the teleporter is invoked:

- We replace `<kernel>` with `(.*?)` and run a regex on the current file name
  for each of the targets and find a match.
- We offer the user a choice of destinations from the remaining targets.
- When selected the kernel is replaced in the selected target
- The file is opened, if it does not exist it is created (using the existing
  create functionality).

```yaml
teleport:
    targets:
        source: 
            pattern: "src/<kernel>.php$"
            create: default
        phpunit: 
            pattern: "tests/Unit/<kernel>Test.php$"
            create: phpunit_test
        benchmark: 
            pattern: "benchmark/<kernel>Bench.php$"
            create: benchmark
```

**Comment by dantleech** [comment]
This could be done:

```
file_inference:
    unit_tests:
         from: lib/
         to: tests/Unit
```
