### ISSUE TITLE
Config refactoring

### ISSUE THREAD

**Issue by dantleech** [phpactor/phpactor#70]
Currently the config is not organized well:

```
autoload: ..
console_dumper_default: 
reflector_stub_directory:
cache_dir:
indentation:
new_class_variants: []
template_paths: []
```

It should be organized by component where suitable:

```
autoload: ..
cache_dir: ...
application:
     console_dumper_default: 
reflection:
    stub_directory:
code_builder:
    indentation: "    "
```

We should also add a command to dump the current configuration
